module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        zinc: {
          50: "rgb(var(--ctp-zinc-50) / <alpha-value>)",
          100: "rgb(var(--ctp-zinc-100) / <alpha-value>)",
          200: "rgb(var(--ctp-zinc-200) / <alpha-value>)",
          300: "rgb(var(--ctp-zinc-300) / <alpha-value>)",
          400: "rgb(var(--ctp-zinc-400) / <alpha-value>)",
          500: "rgb(var(--ctp-zinc-500) / <alpha-value>)",
          600: "rgb(var(--ctp-zinc-600) / <alpha-value>)",
          700: "rgb(var(--ctp-zinc-700) / <alpha-value>)",
          800: "rgb(var(--ctp-zinc-800) / <alpha-value>)",
          900: "rgb(var(--ctp-zinc-900) / <alpha-value>)",
          950: "rgb(var(--ctp-zinc-950) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--ctp-indigo-50) / <alpha-value>)",
          100: "rgb(var(--ctp-indigo-100) / <alpha-value>)",
          200: "rgb(var(--ctp-indigo-200) / <alpha-value>)",
          300: "rgb(var(--ctp-indigo-300) / <alpha-value>)",
          400: "rgb(var(--ctp-indigo-400) / <alpha-value>)",
          500: "rgb(var(--ctp-indigo-500) / <alpha-value>)",
          600: "rgb(var(--ctp-indigo-600) / <alpha-value>)",
          700: "rgb(var(--ctp-indigo-700) / <alpha-value>)",
          800: "rgb(var(--ctp-indigo-800) / <alpha-value>)",
          900: "rgb(var(--ctp-indigo-900) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--ctp-red-50) / <alpha-value>)",
          100: "rgb(var(--ctp-red-100) / <alpha-value>)",
          200: "rgb(var(--ctp-red-200) / <alpha-value>)",
          300: "rgb(var(--ctp-red-300) / <alpha-value>)",
          400: "rgb(var(--ctp-red-400) / <alpha-value>)",
          500: "rgb(var(--ctp-red-500) / <alpha-value>)",
          600: "rgb(var(--ctp-red-600) / <alpha-value>)",
          700: "rgb(var(--ctp-red-700) / <alpha-value>)",
          800: "rgb(var(--ctp-red-800) / <alpha-value>)",
          900: "rgb(var(--ctp-red-900) / <alpha-value>)",
        },
        green: {
          50: "rgb(var(--ctp-green-50) / <alpha-value>)",
          100: "rgb(var(--ctp-green-100) / <alpha-value>)",
          200: "rgb(var(--ctp-green-200) / <alpha-value>)",
          300: "rgb(var(--ctp-green-300) / <alpha-value>)",
          400: "rgb(var(--ctp-green-400) / <alpha-value>)",
          500: "rgb(var(--ctp-green-500) / <alpha-value>)",
          600: "rgb(var(--ctp-green-600) / <alpha-value>)",
          700: "rgb(var(--ctp-green-700) / <alpha-value>)",
          800: "rgb(var(--ctp-green-800) / <alpha-value>)",
          900: "rgb(var(--ctp-green-900) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--ctp-amber-50) / <alpha-value>)",
          100: "rgb(var(--ctp-amber-100) / <alpha-value>)",
          200: "rgb(var(--ctp-amber-200) / <alpha-value>)",
          300: "rgb(var(--ctp-amber-300) / <alpha-value>)",
          400: "rgb(var(--ctp-amber-400) / <alpha-value>)",
          500: "rgb(var(--ctp-amber-500) / <alpha-value>)",
          600: "rgb(var(--ctp-amber-600) / <alpha-value>)",
          700: "rgb(var(--ctp-amber-700) / <alpha-value>)",
          800: "rgb(var(--ctp-amber-800) / <alpha-value>)",
          900: "rgb(var(--ctp-amber-900) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--ctp-sky-50) / <alpha-value>)",
          100: "rgb(var(--ctp-sky-100) / <alpha-value>)",
          200: "rgb(var(--ctp-sky-200) / <alpha-value>)",
          300: "rgb(var(--ctp-sky-300) / <alpha-value>)",
          400: "rgb(var(--ctp-sky-400) / <alpha-value>)",
          500: "rgb(var(--ctp-sky-500) / <alpha-value>)",
          600: "rgb(var(--ctp-sky-600) / <alpha-value>)",
          700: "rgb(var(--ctp-sky-700) / <alpha-value>)",
          800: "rgb(var(--ctp-sky-800) / <alpha-value>)",
          900: "rgb(var(--ctp-sky-900) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--ctp-purple-50) / <alpha-value>)",
          100: "rgb(var(--ctp-purple-100) / <alpha-value>)",
          200: "rgb(var(--ctp-purple-200) / <alpha-value>)",
          300: "rgb(var(--ctp-purple-300) / <alpha-value>)",
          400: "rgb(var(--ctp-purple-400) / <alpha-value>)",
          500: "rgb(var(--ctp-purple-500) / <alpha-value>)",
          600: "rgb(var(--ctp-purple-600) / <alpha-value>)",
          700: "rgb(var(--ctp-purple-700) / <alpha-value>)",
          800: "rgb(var(--ctp-purple-800) / <alpha-value>)",
          900: "rgb(var(--ctp-purple-900) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--ctp-blue-50) / <alpha-value>)",
          100: "rgb(var(--ctp-blue-100) / <alpha-value>)",
          200: "rgb(var(--ctp-blue-200) / <alpha-value>)",
          300: "rgb(var(--ctp-blue-300) / <alpha-value>)",
          400: "rgb(var(--ctp-blue-400) / <alpha-value>)",
          500: "rgb(var(--ctp-blue-500) / <alpha-value>)",
          600: "rgb(var(--ctp-blue-600) / <alpha-value>)",
          700: "rgb(var(--ctp-blue-700) / <alpha-value>)",
          800: "rgb(var(--ctp-blue-800) / <alpha-value>)",
          900: "rgb(var(--ctp-blue-900) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};